namespace: manuelraa
name: yaml_folder_inventory
<<<<<<< HEAD
version: 1.2.3
=======
version: 1.2.2
>>>>>>> origin/master
readme: README.md
authors:
  - Manuel Rapp (https://github.com/Manuelraa)
description: Recursive folder based yaml inventory
license_file: LICENSE
tags: [inventory, plugin]
repository: https://github.com/Manuelraa/yaml_folder_inventory
documentation: null
homepage: https://github.com/Manuelraa/yaml_folder_inventory
issues: https://github.com/Manuelraa/yaml_folder_inventory/issues
